git:
  diffContextSize: 10
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
gui:
  theme:
    selectedLineBgColor:
      - "#444444"
    selectedRangeBgColor:
      - "#444444"
